Update README.md
ganga-devs/GangaGSoC2024 pull request #6
Opened 2021-03-03 09:25 UTC by egede

Update to GSoC2021

2021-03-03 09:31 UTC, alexanderrichards requested changes
Looks good. The task descriptions are clearer I think now. Just some minor typos

2021-03-03 09:31 UTC, alexanderrichards commented on README.md
> +  - Create a a second job in Ganga that will count the number of occurences of the word "it" in the text of the PDF file. It should be counted whether it is capitalised or not. Make sure not to count
```suggestion
  - Create a a second job in Ganga that will count the number of occurences of the word "it" in the text of the PDF file. It should be counted whether it is capitalised or not. Make sure not to count other words that have the letters "it" inside them. So "It is best when it uses Ganga" should have a count of two, while "The initial test did no work" should have a count of zero.
```

2021-03-03 09:31 UTC, alexanderrichards commented on README.md
> + - Modify the server to allow updating of the content either by making it a RESTful service.
```suggestion
 - Modify the server to allow updating of the content by making it a RESTful service.
```

2021-03-03 09:48 UTC, alexanderrichards approved these changes

2021-03-03 09:48 UTC, merged

2021-03-03 23:40 UTC, mesmith75 commented
Very nice. My only comment would be that for the GUI the technology is now pretty set by what is there. Do we want to prescribe proficiency in that?

2021-03-04 00:14 UTC, egede commented
> My only comment would be that for the GUI the technology is now pretty set by what is there. Do we want to require proficiency in that?
Can anybody include the buzz words to achieve that?

2021-03-04 09:28 UTC, alexanderrichards commented
> > My only comment would be that for the GUI the technology is now pretty set by what is there. Do we want to require proficiency in that?
> 
> Can anybody include the buzz words to achieve that?

I suspect that simply requiring them to use the Flask framework would suffice. I'll put in a PR